---
# nginxがインストールされている
- name: Ensure nginx repository is installed
  yum: name={{ nginx_repository[ansible_distribution_major_version] }} state=installed
- name: Ensure nginx is installed
  yum: name=nginx state=latest

# nginxが自動起動設定済み
- name: Ensure nginx service is enable
  service: name=nginx enabled=yes

# nginxが起動済み
- name: Ensure nginx service is started
  service: name=nginx state=started

# iptablesが利用可能かどうかチェック
- name: Check iptables is enabled
  file: path=/etc/sysconfig/iptables state=file
  register: is_iptables_enabled
  ignore_errors: yes

# HTTPポート解放済み
- name: Ensure http port is opend (iptables)
  lineinfile: dest=/etc/sysconfig/iptables insertafter='^:OUTPUT' line="-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT"
  when: is_iptables_enabled|success
  notify: Restart iptables
- name: Ensure http port is opened (firewall-cmd)
  firewalld: service=http permanent=true state=enabled
  when: is_iptables_enabled|failed
  notify: Restart firewalld
