---
# EncFSビルドに必要なツールがインストールされている
- name: Ensure EncFS build tools are installed
  yum: name={{ item.name }} state={{ item.state }}
  with_items: encfs_build_tools

# fuseモジュールがロードされているかチェック
- name: Check fuse module is loaded
  shell: lsmod | grep fuse
  register: is_fuse_module_loaded
  ignore_errors: yes

# fuseモジュールロード済み
- name: Ensure fuse module is loaded
  shell: modprobe fuse
  when: is_fuse_module_loaded|failed

# EncFSソースダウンロード済み
- name: Ensure EncFS src exist
  get_url: url={{ encfs_uri }} dest={{ encfs_src_prefix }}

# EncFSソース解凍済み
- name: Ensure EncFS src is unarchived
  shell: tar xvfz encfs-{{ encfs_version }}.tar.gz
  args:
    chdir: "{{ encfs_src_prefix }}"
    creates: "{{ encfs_src_prefix }}/encfs-{{ encfs_version }}"

# EncFSインストール済み
- name: Ensure EncFS is installed
  shell: >
    {{ encfs_build_env }} autoreconf -if &&
    {{ encfs_build_env }} ./configure --prefix={{ encfs_prefix }} &&
    make && make install
  args:
    chdir: "{{ encfs_src_prefix }}/encfs-{{ encfs_version }}"
    creates: /usr/local/bin/encfs
