---
# Redmine 添付ファイルデータの暗号化
- include: redmine_files.yml
# MySQL RedmineDBデータの暗号化
- include: redmine_db.yml

# 起動/停止スクリプトの配置
- name: Ensure encRedmine_ctr exists
  template: src=encRedmine_ctl.j2 dest=/opt/encRedmine mode=700 owner=root group=root
