---
# Redmine 添付ファイルデータの暗号化
- include: redmine_files.yml
# MySQL RedmineDBデータの暗号化
- include: redmine_db.yml

# 起動/停止スクリプトの配置
- name: Ensure encRedmineCtl exists
  template: src=encRedmineCtl.j2 dest=/opt/encRedmineCtl mode=700 owner=root group=root
